In [2]:
import pandas as pd

In [9]:
data=pd.read_csv("SST11.04.2022.csv")

In [10]:
data

,MH2,MH3,MH5,SAP,SSN,DESCRIPTION,Sales Quantity,Online Sales Quantity,% Online Sales,Gross Sales,Margin %,Total Stock,DC Stock,Total Wks Cover,DC Cover
0,FOOTWEAR_WOMEN,WOMEN_PERF_FW,LDSRUNFW,1122863,22Q1,Brooks Adrenaline GTS 22 Wmn Fw Blk/Purp,147,16.0,10.88%,"21,545",49.60%,529,91,3.6,0.62
1,KEEPFIT,KPF_MACHINE,KPFTTREAD,1090345,21/22,ProForm 525i Treadmill Black,24,22.0,91.67%,"17,474",21.90%,114,100,4.75,4.17
2,FOOTWEAR_WOMEN,WOMEN_PERF_FW,LDSRUNFW,1122860,22Q1,Brooks Ghost 14 Womens Fw Black,83,10.0,12.05%,"12,030",49.10%,1143,509,13.77,6.13
3,FOOTWEAR_MEN,MEN_PERF_FW,MENSRUNFW,1122887,22Q1,Brooks Adrenaline GTS 22 Mens Fw Navy,79,8.0,10.13%,"11,438",49.00%,1210,503,15.32,6.37
4,FOOTWEAR_WOMEN,WOMEN_PERF_FW,LDSRUNFW,1122865,22Q1,Brooks Adrenaline GTS 22 Wmns Fw Black,71,11.0,15.49%,"10,408",49.70%,928,481,13.07,6.77
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5912,KEEPFIT,ATHLETICS_ACC,ATH_TECH,1125310,NOOS,Fitbit Charge 5 White,-1,-1.0,100.00%,-159,6.70%,57,43,-57,-43
5913,FOOTBALL_BOOT,SCR_FOOTWEAR,SCR_TRAX,1118434,21Q3,Puma FUTURE Z 1.2 FG/AG Green,-1,NaN,0.00%,-200,-52.60%,6,4,-6,-4
5914,FOOTBALL_BOOT,SCR_FOOTWEAR,SCR_FBOOT,1117634,P2201,adidas X Speedflow.1 SG Black,-1,-1.0,100.00%,-220,-47.40%,3,0,-3,0
5915,FOOTBALL_BOOT,SCR_FOOTWEAR,SCR_TRAX,1125637,22Q1,Adidas PREDATOR EDGE.1 FG Black,-1,1.0,-100.00%,-231,-49.90%,13,5,-13,-5
5916,KEEPFIT,ATHLETICS_ACC,ATH_TECH,1113875,NOOS,Garmin Forerunner 245 Berry,-1,NaN,0.00%,-285,-100.00%,4,1,-4,-1

In [11]:
data.shape

(5917, 15)

In [12]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5917 entries, 0 to 5916
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   MH2                    5917 non-null   object
 1   MH3                    5917 non-null   object
 2   MH5                    5917 non-null   object
 3   SAP                    5917 non-null   int64
 4   SSN                    5917 non-null   object
 5   DESCRIPTION            5917 non-null   object
 6   Sales Quantity         5917 non-null   int64
 7   Online Sales Quantity  2921 non-null   float64
 8   % Online Sales         5917 non-null   object
 9   Gross Sales            5917 non-null   object
 10  Margin %               5917 non-null   object
 11  Total Stock            5917 non-null   int64
 12  DC Stock               5917 non-null   int64
 13  Total Wks Cover        5917 non-null   object
 14  DC Cover               5917 non-null   object
dtypes: float64(1), int64(4), object(10)
memory usage: 693.5+ KB

In [13]:
data.describe()

,SAP,Sales Quantity,Online Sales Quantity,Total Stock,DC Stock
count,5.917000e+03,5917.000000,2921.000000,5917.000000,5917.000000
mean,3.093738e+06,11.660301,3.258473,194.856008,101.735508
std,1.273015e+07,24.278094,5.367452,380.871926,264.179586
min,1.000000e+03,-5.000000,-5.000000,-102.000000,0.000000
25%,1.111601e+06,1.000000,1.000000,13.000000,1.000000
50%,1.117843e+06,3.000000,2.000000,54.000000,17.000000
75%,1.122886e+06,11.000000,4.000000,201.000000,77.000000
max,1.057840e+08,410.000000,125.000000,9154.000000,7087.000000

In [17]:
data[['DESCRIPTION', '% Online Sales']]

                                   DESCRIPTION % Online Sales
0     Brooks Adrenaline GTS 22 Wmn Fw Blk/Purp         10.88%
1                 ProForm 525i Treadmill Black         91.67%
2              Brooks Ghost 14 Womens Fw Black         12.05%
3        Brooks Adrenaline GTS 22 Mens Fw Navy         10.13%
4       Brooks Adrenaline GTS 22 Wmns Fw Black         15.49%
...                                        ...            ...
5912                     Fitbit Charge 5 White        100.00%
5913             Puma FUTURE Z 1.2 FG/AG Green          0.00%
5914             adidas X Speedflow.1 SG Black        100.00%
5915           Adidas PREDATOR EDGE.1 FG Black       -100.00%
5916               Garmin Forerunner 245 Berry          0.00%

[5917 rows x 2 columns]

In [18]:
data['DESCRIPTION']

0       Brooks Adrenaline GTS 22 Wmn Fw Blk/Purp
1                   ProForm 525i Treadmill Black
2                Brooks Ghost 14 Womens Fw Black
3          Brooks Adrenaline GTS 22 Mens Fw Navy
4         Brooks Adrenaline GTS 22 Wmns Fw Black
                          ...
5912                       Fitbit Charge 5 White
5913               Puma FUTURE Z 1.2 FG/AG Green
5914               adidas X Speedflow.1 SG Black
5915             Adidas PREDATOR EDGE.1 FG Black
5916                 Garmin Forerunner 245 Berry
Name: DESCRIPTION, Length: 5917, dtype: object

In [19]:
type(data[['DESCRIPTION', '% Online Sales']])

pandas.core.frame.DataFrame

In [20]:
type(data['DESCRIPTION'])

pandas.core.series.Series

In [22]:
data[1:6]

,MH2,MH3,MH5,SAP,SSN,DESCRIPTION,Sales Quantity,Online Sales Quantity,% Online Sales,Gross Sales,Margin %,Total Stock,DC Stock,Total Wks Cover,DC Cover
1,KEEPFIT,KPF_MACHINE,KPFTTREAD,1090345,21/22,ProForm 525i Treadmill Black,24,22.0,91.67%,"17,474",21.90%,114,100,4.75,4.17
2,FOOTWEAR_WOMEN,WOMEN_PERF_FW,LDSRUNFW,1122860,22Q1,Brooks Ghost 14 Womens Fw Black,83,10.0,12.05%,"12,030",49.10%,1143,509,13.77,6.13
3,FOOTWEAR_MEN,MEN_PERF_FW,MENSRUNFW,1122887,22Q1,Brooks Adrenaline GTS 22 Mens Fw Navy,79,8.0,10.13%,"11,438",49.00%,1210,503,15.32,6.37
4,FOOTWEAR_WOMEN,WOMEN_PERF_FW,LDSRUNFW,1122865,22Q1,Brooks Adrenaline GTS 22 Wmns Fw Black,71,11.0,15.49%,"10,408",49.70%,928,481,13.07,6.77
5,RUGBY,RUGBY_REPLICA,RIRE_TK,1118068,21Q3,Canterbury IRFU 21 Home Pro Jersey Green,165,51.0,30.91%,"9,938",27.00%,4606,3494,27.92,21.18

In [23]:
data.head()

,MH2,MH3,MH5,SAP,SSN,DESCRIPTION,Sales Quantity,Online Sales Quantity,% Online Sales,Gross Sales,Margin %,Total Stock,DC Stock,Total Wks Cover,DC Cover
0,FOOTWEAR_WOMEN,WOMEN_PERF_FW,LDSRUNFW,1122863,22Q1,Brooks Adrenaline GTS 22 Wmn Fw Blk/Purp,147,16.0,10.88%,"21,545",49.60%,529,91,3.6,0.62
1,KEEPFIT,KPF_MACHINE,KPFTTREAD,1090345,21/22,ProForm 525i Treadmill Black,24,22.0,91.67%,"17,474",21.90%,114,100,4.75,4.17
2,FOOTWEAR_WOMEN,WOMEN_PERF_FW,LDSRUNFW,1122860,22Q1,Brooks Ghost 14 Womens Fw Black,83,10.0,12.05%,"12,030",49.10%,1143,509,13.77,6.13
3,FOOTWEAR_MEN,MEN_PERF_FW,MENSRUNFW,1122887,22Q1,Brooks Adrenaline GTS 22 Mens Fw Navy,79,8.0,10.13%,"11,438",49.00%,1210,503,15.32,6.37
4,FOOTWEAR_WOMEN,WOMEN_PERF_FW,LDSRUNFW,1122865,22Q1,Brooks Adrenaline GTS 22 Wmns Fw Black,71,11.0,15.49%,"10,408",49.70%,928,481,13.07,6.77

In [32]:
data.loc[:, ['DESCRIPTION', "% Online Sales"]]

                                   DESCRIPTION % Online Sales
0     Brooks Adrenaline GTS 22 Wmn Fw Blk/Purp         10.88%
1                 ProForm 525i Treadmill Black         91.67%
2              Brooks Ghost 14 Womens Fw Black         12.05%
3        Brooks Adrenaline GTS 22 Mens Fw Navy         10.13%
4       Brooks Adrenaline GTS 22 Wmns Fw Black         15.49%
...                                        ...            ...
5912                     Fitbit Charge 5 White        100.00%
5913             Puma FUTURE Z 1.2 FG/AG Green          0.00%
5914             adidas X Speedflow.1 SG Black        100.00%
5915           Adidas PREDATOR EDGE.1 FG Black       -100.00%
5916               Garmin Forerunner 245 Berry          0.00%

[5917 rows x 2 columns]

In [33]:
data.loc[:, ['SAP','DESCRIPTION', "% Online Sales"]]

          SAP                               DESCRIPTION % Online Sales
0     1122863  Brooks Adrenaline GTS 22 Wmn Fw Blk/Purp         10.88%
1     1090345              ProForm 525i Treadmill Black         91.67%
2     1122860           Brooks Ghost 14 Womens Fw Black         12.05%
3     1122887     Brooks Adrenaline GTS 22 Mens Fw Navy         10.13%
4     1122865    Brooks Adrenaline GTS 22 Wmns Fw Black         15.49%
...       ...                                       ...            ...
5912  1125310                     Fitbit Charge 5 White        100.00%
5913  1118434             Puma FUTURE Z 1.2 FG/AG Green          0.00%
5914  1117634             adidas X Speedflow.1 SG Black        100.00%
5915  1125637           Adidas PREDATOR EDGE.1 FG Black       -100.00%
5916  1113875               Garmin Forerunner 245 Berry          0.00%

[5917 rows x 3 columns]

In [37]:
missing_values_count = data.isna().sum()

In [40]:
print(missing_values_count[0:14])

MH2                         0
MH3                         0
MH5                         0
SAP                         0
SSN                         0
DESCRIPTION                 0
Sales Quantity              0
Online Sales Quantity    2996
% Online Sales              0
Gross Sales                 0
Margin %                    0
Total Stock                 0
DC Stock                    0
Total Wks Cover             0
dtype: int64

In [41]:
data_cleaned = data.fillna(0)

In [44]:
print(data_cleaned.shape)

(5917, 15)

In [47]:
data_cleaned.describe

<bound method NDFrame.describe of                  MH2            MH3        MH5      SAP    SSN  \
0     FOOTWEAR_WOMEN  WOMEN_PERF_FW   LDSRUNFW  1122863   22Q1
1            KEEPFIT    KPF_MACHINE  KPFTTREAD  1090345  21/22
2     FOOTWEAR_WOMEN  WOMEN_PERF_FW   LDSRUNFW  1122860   22Q1
3       FOOTWEAR_MEN    MEN_PERF_FW  MENSRUNFW  1122887   22Q1
4     FOOTWEAR_WOMEN  WOMEN_PERF_FW   LDSRUNFW  1122865   22Q1
...              ...            ...        ...      ...    ...
5912         KEEPFIT  ATHLETICS_ACC   ATH_TECH  1125310   NOOS
5913   FOOTBALL_BOOT   SCR_FOOTWEAR   SCR_TRAX  1118434   21Q3
5914   FOOTBALL_BOOT   SCR_FOOTWEAR  SCR_FBOOT  1117634  P2201
5915   FOOTBALL_BOOT   SCR_FOOTWEAR   SCR_TRAX  1125637   22Q1
5916         KEEPFIT  ATHLETICS_ACC   ATH_TECH  1113875   NOOS

                                   DESCRIPTION  Sales Quantity  \
0     Brooks Adrenaline GTS 22 Wmn Fw Blk/Purp             147
1                 ProForm 525i Treadmill Black              24
2              Brooks Ghost 14 Womens Fw Black              83
3        Brooks Adrenaline GTS 22 Mens Fw Navy              79
4       Brooks Adrenaline GTS 22 Wmns Fw Black              71
...                                        ...             ...
5912                     Fitbit Charge 5 White              -1
5913             Puma FUTURE Z 1.2 FG/AG Green              -1
5914             adidas X Speedflow.1 SG Black              -1
5915           Adidas PREDATOR EDGE.1 FG Black              -1
5916               Garmin Forerunner 245 Berry              -1

      Online Sales Quantity % Online Sales Gross Sales  Margin %  \
0                      16.0         10.88%      21,545    49.60%
1                      22.0         91.67%      17,474    21.90%
2                      10.0         12.05%      12,030    49.10%
3                       8.0         10.13%      11,438    49.00%
4                      11.0         15.49%      10,408    49.70%
...                     ...            ...         ...       ...
5912                   -1.0        100.00%        -159     6.70%
5913                    0.0          0.00%        -200   -52.60%
5914                   -1.0        100.00%        -220   -47.40%
5915                    1.0       -100.00%        -231   -49.90%
5916                    0.0          0.00%        -285  -100.00%

      Total Stock   DC Stock  Total Wks Cover DC Cover
0              529         91             3.6     0.62
1              114        100            4.75     4.17
2             1143        509           13.77     6.13
3             1210        503           15.32     6.37
4              928        481           13.07     6.77
...            ...        ...             ...      ...
5912            57         43             -57      -43
5913             6          4              -6       -4
5914             3          0              -3        0
5915            13          5             -13       -5
5916             4          1              -4       -1

[5917 rows x 15 columns]>

In [48]:
data_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5917 entries, 0 to 5916
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   MH2                    5917 non-null   object
 1   MH3                    5917 non-null   object
 2   MH5                    5917 non-null   object
 3   SAP                    5917 non-null   int64
 4   SSN                    5917 non-null   object
 5   DESCRIPTION            5917 non-null   object
 6   Sales Quantity         5917 non-null   int64
 7   Online Sales Quantity  5917 non-null   float64
 8   % Online Sales         5917 non-null   object
 9   Gross Sales            5917 non-null   object
 10  Margin %               5917 non-null   object
 11  Total Stock            5917 non-null   int64
 12  DC Stock               5917 non-null   int64
 13  Total Wks Cover        5917 non-null   object
 14  DC Cover               5917 non-null   object
dtypes: float64(1), int64(4), object(10)
memory usage: 693.5+ KB

In [49]:
data_cleaned.drop_duplicates()

,MH2,MH3,MH5,SAP,SSN,DESCRIPTION,Sales Quantity,Online Sales Quantity,% Online Sales,Gross Sales,Margin %,Total Stock,DC Stock,Total Wks Cover,DC Cover
0,FOOTWEAR_WOMEN,WOMEN_PERF_FW,LDSRUNFW,1122863,22Q1,Brooks Adrenaline GTS 22 Wmn Fw Blk/Purp,147,16.0,10.88%,"21,545",49.60%,529,91,3.6,0.62
1,KEEPFIT,KPF_MACHINE,KPFTTREAD,1090345,21/22,ProForm 525i Treadmill Black,24,22.0,91.67%,"17,474",21.90%,114,100,4.75,4.17
2,FOOTWEAR_WOMEN,WOMEN_PERF_FW,LDSRUNFW,1122860,22Q1,Brooks Ghost 14 Womens Fw Black,83,10.0,12.05%,"12,030",49.10%,1143,509,13.77,6.13
3,FOOTWEAR_MEN,MEN_PERF_FW,MENSRUNFW,1122887,22Q1,Brooks Adrenaline GTS 22 Mens Fw Navy,79,8.0,10.13%,"11,438",49.00%,1210,503,15.32,6.37
4,FOOTWEAR_WOMEN,WOMEN_PERF_FW,LDSRUNFW,1122865,22Q1,Brooks Adrenaline GTS 22 Wmns Fw Black,71,11.0,15.49%,"10,408",49.70%,928,481,13.07,6.77
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5912,KEEPFIT,ATHLETICS_ACC,ATH_TECH,1125310,NOOS,Fitbit Charge 5 White,-1,-1.0,100.00%,-159,6.70%,57,43,-57,-43
5913,FOOTBALL_BOOT,SCR_FOOTWEAR,SCR_TRAX,1118434,21Q3,Puma FUTURE Z 1.2 FG/AG Green,-1,0.0,0.00%,-200,-52.60%,6,4,-6,-4
5914,FOOTBALL_BOOT,SCR_FOOTWEAR,SCR_FBOOT,1117634,P2201,adidas X Speedflow.1 SG Black,-1,-1.0,100.00%,-220,-47.40%,3,0,-3,0
5915,FOOTBALL_BOOT,SCR_FOOTWEAR,SCR_TRAX,1125637,22Q1,Adidas PREDATOR EDGE.1 FG Black,-1,1.0,-100.00%,-231,-49.90%,13,5,-13,-5
5916,KEEPFIT,ATHLETICS_ACC,ATH_TECH,1113875,NOOS,Garmin Forerunner 245 Berry,-1,0.0,0.00%,-285,-100.00%,4,1,-4,-1

In [50]:
data_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5917 entries, 0 to 5916
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   MH2                    5917 non-null   object
 1   MH3                    5917 non-null   object
 2   MH5                    5917 non-null   object
 3   SAP                    5917 non-null   int64
 4   SSN                    5917 non-null   object
 5   DESCRIPTION            5917 non-null   object
 6   Sales Quantity         5917 non-null   int64
 7   Online Sales Quantity  5917 non-null   float64
 8   % Online Sales         5917 non-null   object
 9   Gross Sales            5917 non-null   object
 10  Margin %               5917 non-null   object
 11  Total Stock            5917 non-null   int64
 12  DC Stock               5917 non-null   int64
 13  Total Wks Cover        5917 non-null   object
 14  DC Cover               5917 non-null   object
dtypes: float64(1), int64(4), object(10)
memory usage: 693.5+ KB